# CAGRA parameter configurations (decoupled from data size)
# cagra_params:
#   intermediate_graph_degree: [32, 64, 128]
#   graph_degree: [8, 16, 32, 64]
#   itopk_size: [64, 128, 256]
#   search_width: [2, 4, 8, 16]
#   max_search_iterations: [0]
#   topk: [10]

cagra_params:
  intermediate_graph_degree: [32]
  graph_degree: [8]
  itopk_size: [64]
  search_width: [2]
  max_search_iterations: [0]
  topk: [10]

# HNSW parameter configurations
# hnsw_params:
#   'M': [16, 32]
#   'efConstruction': [32, 64, 128, 256, 512]
#   'efSearch': [8, 16, 32, 64, 128, 256, 512, 768, 1024]
#   'topk': [10]

hnsw_params:
  'M': [16]
  'efConstruction': [32]
  'efSearch': [8]
  'topk': [10]

# Data sizes to evaluate
data_sizes: [50000]

# Global settings
global_settings:
  num_queries: 10000
  batch_size: 100
  num_workers_params: 1
  num_workers_throughput: 2
  persistent: false
  run_time_seconds: 30

# Exclude specific parameter combinations
exclude_combinations: []

# Results directory settings
results_settings:
  results_dir: "comprehensive_comparison_results"
  save_intermediate: true
  cleanup_pause_seconds: 30