# CAGRA parameter configurations (decoupled from data size)
cagra_params:
  intermediate_graph_degree: [32, 64, 96, 128]
  graph_degree: [32, 64, 96, 128]
  itopk_size: [32, 64, 128, 256, 512]
  search_width: [1, 2, 4, 8, 16, 32, 64]
  max_search_iterations: [0]
  topk: [10]

# HNSW parameter configurations
hnsw_params:
  'M': [16, 32]
  'efConstruction': [32, 64, 128, 256, 512]
  'efSearch': [8, 16, 32, 64, 128, 256, 512, 768, 1024]
  'topk': [10]

# Data sizes to evaluate
data_sizes: [5000000]

# Global settings
global_settings:
  num_queries: 10000
  batch_size: 100
  num_workers_params: 1
  persistent: false
  run_time_seconds: 30

# Exclude specific parameter combinations
exclude_combinations: []

# Results directory settings
results_settings:
  results_dir: "comprehensive_comparison_results"
  save_intermediate: true
  cleanup_pause_seconds: 10